#!/usr/bin/env python3
"""
Answer Distribution Analysis Tool

This script analyzes the distribution of answers generated by sampling from
a reasoning chain multiple times. It helps understand answer variability and
confidence by generating multiple completions and analyzing the distribution
of extracted answers.

Usage:
    python run_distribution.py --result experiments/exp/shuffle_word/results.json \\
                                --out exp/shuffle_word/distributions.json \\
                                --n 100 \\
                                --answer_free_gen

Features:
    - Multiple sampling from reasoning chains (n times)
    - Answer extraction from $\\boxed{...}$ format
    - Answer normalization using sympy for mathematical equivalence
    - Distribution calculation with ranking and correctness checking
    - Resume capability using JSONL strategy
    - Parallel execution for efficiency
"""

import json
import re
import argparse
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from tqdm import tqdm
import logging
from datetime import datetime

from llm_client import LLMClient, Task, CompletionRequest
from logger_config import setup_logger
from core import (
    build_gpt_oss_prompt_with_reasoning,
    build_gpt_oss_prompt_with_reasoning_prefilled_answer,
    append_to_jsonl,
    load_from_jsonl
)

# Setup logger
logger = setup_logger(__name__, log_file='logs/run_distribution.log')

# Default settings
DEFAULT_MAX_WORKERS = 300
DEFAULT_N_SAMPLES = 50
DEFAULT_TEMPERATURE = 0.5

PREFILL_TEXT = "Thus, the answer is"


# =============================================================================
# Answer Extraction
# =============================================================================

def extract_answer_from_completion(completion: str) -> Optional[str]:
    """
    Extract answer from completion text using numeric pattern [0-9]+.

    Takes the last occurrence if multiple numeric matches exist.

    Args:
        completion: Generated text from LLM

    Returns:
        Extracted answer string (numeric), or None if no number found

    Examples:
        >>> extract_answer_from_completion("The answer is 42")
        '42'
        >>> extract_answer_from_completion("First 10 then 20")
        '20'
        >>> extract_answer_from_completion("No answer here")
        None
        >>> extract_answer_from_completion("The result: 123")
        '123'
    """
    # Pattern matches one or more digits
    pattern = r'[0-9]+'

    matches = re.findall(pattern, completion)

    if not matches:
        return None

    # Take the last match
    answer = matches[-1].strip()

    # Return None if empty
    if not answer:
        return None

    return answer


# =============================================================================
# Answer Normalization
# =============================================================================

def normalize_answer(answer: str) -> Optional[str]:
    """
    Normalize mathematical answer using sympy for equivalence checking.

    Converts mathematical expressions to canonical form so that equivalent
    answers (e.g., "1/2" and "2/4") map to the same normalized form.

    Args:
        answer: Raw answer string

    Returns:
        Normalized answer string, or original if normalization fails

    Examples:
        >>> normalize_answer("2/4")
        '1/2'
        >>> normalize_answer("42.0")
        '42'
        >>> normalize_answer("not a number")
        'not a number'
    """
    import sympy as sp

    if not answer:
        return None

    # Strip whitespace
    answer = answer.strip()

    try:
        # Try to parse as sympy expression
        # Handle LaTeX fractions
        answer_processed = answer.replace('\\frac', 'Rational')
        answer_processed = re.sub(r'Rational\{(\d+)\}\{(\d+)\}', r'Rational(\1, \2)', answer_processed)

        expr = sp.sympify(answer_processed)

        # Simplify and convert to string
        simplified = sp.simplify(expr)

        # Convert floats to integers if they are whole numbers
        if simplified.is_Float:
            if simplified % 1 == 0:
                normalized = str(int(simplified))
            else:
                normalized = str(simplified)
        else:
            normalized = str(simplified)

        return normalized

    except (sp.SympifyError, ValueError, TypeError, AttributeError) as e:
        # If parsing fails, return original string
        logger.debug(f"Failed to normalize '{answer}': {e}")
        return answer


# =============================================================================
# Entropy Calculation
# =============================================================================

def calculate_entropy(distribution: List[Dict]) -> float:
    """
    Calculate Shannon entropy of an answer distribution.

    Entropy measures the uncertainty/randomness in the distribution.
    Higher entropy means more diverse answers, lower entropy means
    more concentrated on a single answer.

    Args:
        distribution: List of distribution entries with 'percentage' field

    Returns:
        Shannon entropy value (in bits). Returns 0 for empty distribution.

    Examples:
        >>> # Uniform distribution: maximum entropy
        >>> dist = [
        ...     {'answer': 'A', 'percentage': 0.5},
        ...     {'answer': 'B', 'percentage': 0.5}
        ... ]
        >>> entropy = calculate_entropy(dist)
        >>> abs(entropy - 1.0) < 0.01  # Should be 1.0
        True

        >>> # Single answer: minimum entropy (0)
        >>> dist = [{'answer': 'A', 'percentage': 1.0}]
        >>> calculate_entropy(dist)
        0.0

        >>> # Empty distribution
        >>> calculate_entropy([])
        0
    """
    import math

    if not distribution:
        return 0

    return -sum(
        d['percentage'] * math.log2(d['percentage'])
        for d in distribution
        if d['percentage'] > 0
    )


# =============================================================================
# Distribution Statistics
# =============================================================================

def calculate_distribution_stats(results: List[Dict]) -> Dict[str, Optional[float]]:
    """
    Calculate comprehensive statistics from distribution results.

    Computes:
    - avg_entropy: Average Shannon entropy across all questions
    - avg_answer_prob: Average probability of correct answer
    - mean_rank: Average rank of correct answer
    - std_rank: Standard deviation of correct answer ranks
    - top1_accuracy: Proportion of questions where correct answer is at rank 1

    Args:
        results: List of result dicts, each containing a 'distribution' field

    Returns:
        Dictionary with keys: avg_entropy, avg_answer_prob, mean_rank, std_rank, top1_accuracy
        Values are None if no valid data available

    Examples:
        >>> results = [
        ...     {
        ...         "distribution": [
        ...             {"answer": "42", "percentage": 0.6, "is_correct": True, "rank": 1},
        ...             {"answer": "43", "percentage": 0.4, "is_correct": False, "rank": 2},
        ...         ]
        ...     },
        ... ]
        >>> stats = calculate_distribution_stats(results)
        >>> stats['avg_answer_prob']
        0.6
        >>> stats['top1_accuracy']
        1.0
    """
    entropies = []
    answer_probs = []
    correct_ranks = []
    top1_correct_count = 0

    for result in results:
        distribution = result.get('distribution', [])

        # Skip empty distributions
        if not distribution:
            continue

        # Calculate entropy for this question
        entropy = calculate_entropy(distribution)
        entropies.append(entropy)

        # Find correct answer probability and rank
        correct_prob = 0.0
        correct_rank = None
        max_rank = 0

        for entry in distribution:
            rank = entry.get('rank', 0)
            max_rank = max(max_rank, rank)

            if entry.get('is_correct', False):
                correct_prob = entry.get('percentage', 0.0)
                correct_rank = rank
                break

        # If correct answer not in distribution, use prob=0 and max_rank+1
        answer_probs.append(correct_prob)
        if correct_rank is None:
            correct_rank = max_rank + 1
        correct_ranks.append(correct_rank)

        # Count if correct answer is at rank 1
        if correct_rank == 1:
            top1_correct_count += 1

    # Calculate averages
    avg_entropy = sum(entropies) / len(entropies) if entropies else None
    avg_answer_prob = sum(answer_probs) / len(answer_probs) if answer_probs else None

    # Calculate rank statistics
    if correct_ranks:
        mean_rank = sum(correct_ranks) / len(correct_ranks)
        if len(correct_ranks) == 1:
            std_rank = 0.0
        else:
            import math
            variance = sum((r - mean_rank) ** 2 for r in correct_ranks) / len(correct_ranks)
            std_rank = math.sqrt(variance)

        # Calculate top-1 accuracy
        top1_accuracy = top1_correct_count / len(correct_ranks)
    else:
        mean_rank = None
        std_rank = None
        top1_accuracy = None

    return {
        'avg_entropy': avg_entropy,
        'avg_answer_prob': avg_answer_prob,
        'mean_rank': mean_rank,
        'std_rank': std_rank,
        'top1_accuracy': top1_accuracy
    }


# =============================================================================
# Answer Rank Statistics
# =============================================================================

def calculate_answer_rank_stats(results: List[Dict]) -> Tuple[Optional[float], Optional[float]]:
    """
    Calculate statistics of correct answer ranks across all questions.

    For each question, finds the rank of the correct answer in the distribution.
    If correct answer is not in distribution, uses max_rank + 1.

    Args:
        results: List of result dicts, each containing a 'distribution' field

    Returns:
        Tuple of (mean_rank, std_rank):
        - mean_rank: Average rank of correct answers
        - std_rank: Standard deviation of correct answer ranks
        Returns (None, None) if no valid ranks found

    Examples:
        >>> results = [
        ...     {
        ...         "distribution": [
        ...             {"answer": "42", "is_correct": True, "rank": 1},
        ...             {"answer": "43", "is_correct": False, "rank": 2},
        ...         ]
        ...     },
        ...     {
        ...         "distribution": [
        ...             {"answer": "100", "is_correct": False, "rank": 1},
        ...             {"answer": "150", "is_correct": True, "rank": 2},
        ...         ]
        ...     },
        ... ]
        >>> mean, std = calculate_answer_rank_stats(results)
        >>> mean
        1.5
        >>> std
        0.5
    """
    import math

    correct_answer_ranks = []

    for result in results:
        distribution = result.get('distribution', [])

        # Skip empty distributions
        if not distribution:
            continue

        # Find correct answer rank
        correct_rank = None
        max_rank = 0

        for entry in distribution:
            rank = entry.get('rank', 0)
            max_rank = max(max_rank, rank)

            if entry.get('is_correct', False):
                correct_rank = rank
                break

        # If correct answer not found, use max_rank + 1
        if correct_rank is None:
            correct_rank = max_rank + 1

        correct_answer_ranks.append(correct_rank)

    # Return None if no valid ranks
    if not correct_answer_ranks:
        return None, None

    # Calculate mean
    mean_rank = sum(correct_answer_ranks) / len(correct_answer_ranks)

    # Calculate standard deviation
    if len(correct_answer_ranks) == 1:
        std_rank = 0.0
    else:
        variance = sum((r - mean_rank) ** 2 for r in correct_answer_ranks) / len(correct_answer_ranks)
        std_rank = math.sqrt(variance)

    return mean_rank, std_rank


# =============================================================================
# Distribution Calculation
# =============================================================================

def calculate_distribution(
    samples: List[Dict],
    correct_answer: str
) -> List[Dict]:
    """
    Calculate answer distribution from samples.

    Groups samples by normalized answer, counts occurrences, and ranks by frequency.

    Args:
        samples: List of sample dicts with 'extracted_answer' key
        correct_answer: Ground truth answer for correctness checking

    Returns:
        List of distribution entries sorted by count (descending), each containing:
        - answer: The answer value
        - count: Number of occurrences
        - percentage: Proportion of valid samples
        - is_correct: Whether this matches the ground truth
        - rank: Ranking by frequency (1 = most frequent)

    Examples:
        >>> samples = [
        ...     {"extracted_answer": "42"},
        ...     {"extracted_answer": "42"},
        ...     {"extracted_answer": "43"},
        ... ]
        >>> dist = calculate_distribution(samples, "42")
        >>> len(dist)
        2
        >>> dist[0]['count']
        2
    """
    from collections import Counter

    # Extract and normalize answers, filtering out None
    normalized_answers = []
    raw_to_normalized = {}  # Map to track original answer for each normalized form

    for sample in samples:
        raw_answer = sample.get('extracted_answer')
        if raw_answer is None:
            continue

        normalized = normalize_answer(raw_answer)
        if normalized:
            normalized_answers.append(normalized)
            # Keep first occurrence of raw answer for display
            if normalized not in raw_to_normalized:
                raw_to_normalized[normalized] = raw_answer

    # Count occurrences
    counter = Counter(normalized_answers)

    if not counter:
        return []

    # Normalize correct answer for comparison
    normalized_correct = normalize_answer(correct_answer)

    # Calculate total valid samples
    total_valid = sum(counter.values())

    # Build distribution entries with dense ranking
    # Dense ranking: same count gets same rank, ranks are consecutive (1, 2, 2, 3)
    distribution = []
    current_rank = 1
    prev_count = None

    for normalized_answer, count in counter.most_common():
        # Dense ranking: same count gets same rank
        if prev_count is not None and count != prev_count:
            current_rank += 1

        distribution.append({
            'answer': raw_to_normalized[normalized_answer],  # Use original form for display
            'normalized_answer': normalized_answer,
            'count': count,
            'percentage': count / total_valid if total_valid > 0 else 0,
            'is_correct': normalized_answer == normalized_correct,
            'rank': current_rank
        })

        prev_count = count

    return distribution


# =============================================================================
# Request Building
# =============================================================================

def build_sampling_request(
    question: str,
    processed_reasoning: str,
    answer_free_gen: bool,
    model_type: str,
    temperature: float,
    task_index: int,
    metadata: Optional[Dict] = None
) -> Task:
    """
    Build a sampling request Task for generating answer completions.

    Args:
        question: The question text
        processed_reasoning: Processed reasoning chain to use as prompt
        answer_free_gen: Whether to use answer-free generation (no prefill)
        model_type: Model type to use
        temperature: Sampling temperature
        task_index: Unique index for this task
        metadata: Optional metadata to attach to the task

    Returns:
        Task object ready for execution

    Examples:
        >>> task = build_sampling_request(
        ...     question="What is 2+2?",
        ...     processed_reasoning="Let's think step by step...",
        ...     answer_free_gen=False,
        ...     model_type="gpt-oss",
        ...     temperature=0.5,
        ...     task_index=0
        ... )
        >>> task.request.model_type
        'gpt-oss'
    """
    if answer_free_gen:
        # Answer-free generation: continue from reasoning
        prompt = build_gpt_oss_prompt_with_reasoning(question, processed_reasoning)
        max_tokens = 3000
    else:
        # With answer prefill: "Thus, the answer is"
        prompt = build_gpt_oss_prompt_with_reasoning_prefilled_answer(
            question,
            processed_reasoning,
            prefill_text=PREFILL_TEXT
        )
        max_tokens = 20

    request = CompletionRequest(
        prompt=prompt,
        model_type=model_type,
        temperature=temperature,
        max_tokens=max_tokens
    )

    task = Task(
        index=task_index,
        request=request,
        metadata=metadata or {}
    )

    return task


# =============================================================================
# Response Processing
# =============================================================================

def process_completed_task(
    completed_task: Task,
    answer_free_gen: bool
) -> Dict:
    """
    Convert a completed task to a sample dictionary.

    Args:
        completed_task: Completed task with response
        answer_free_gen: Whether answer-free generation was used

    Returns:
        Dictionary with sample data including extracted answer

    Examples:
        >>> # Mock a successful task
        >>> from llm_client import Response
        >>> task = Task(index=0, request=None, metadata={'sample_id': 0})
        >>> task.response = Response(
        ...     content="\\\\boxed{42}",
        ...     history="",
        ...     elapsed_seconds=1.0,
        ...     success=True
        ... )
        >>> sample = process_completed_task(task, answer_free_gen=False)
        >>> sample['success']
        True
        >>> sample['extracted_answer']
        '42'
    """
    response = completed_task.response
    sample_id = completed_task.metadata.get('sample_id', completed_task.index)

    if response.success and response.content:
        # Add PREFILL_TEXT prefix when not using answer_free_gen
        if answer_free_gen:
            raw_completion = response.content
        else:
            raw_completion = PREFILL_TEXT + response.content

        extracted_answer = extract_answer_from_completion(raw_completion)

        return {
            'sample_id': sample_id,
            'raw_completion': raw_completion,
            'extracted_answer': extracted_answer,
            'success': True
        }
    else:
        return {
            'sample_id': sample_id,
            'raw_completion': None,
            'extracted_answer': None,
            'success': False,
            'error': response.err_message
        }


# =============================================================================
# Main Execution Helper Functions
# =============================================================================

def load_and_validate_input(args):
    """
    Load and validate input data from results.json

    Returns:
        Tuple of (results, experiment_metadata, model_type, output_paths)
        where output_paths is (sampling_jsonl, output_json)
    """
    print(f"\nLoading results from {args.result}...")
    with open(args.result, 'r', encoding='utf-8') as f:
        input_data = json.load(f)

    results = input_data.get('results', [])
    experiment_metadata = input_data.get('experiment_metadata', {})

    # Extract model_type from metadata
    model_type = experiment_metadata.get('model_type', 'gpt-oss')
    print(f"Detected model type: {model_type}")

    if args.limit:
        results = results[:args.limit]
        print(f"Limited to {args.limit} questions")

    print(f"Total questions: {len(results)}")

    # Prepare output paths (JSONL strategy)
    output_path = Path(args.out)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    sampling_jsonl = output_path.parent / f"{output_path.stem}_sampling.jsonl"
    output_json = output_path

    print(f"Sampling JSONL: {sampling_jsonl}")
    print(f"Final JSON:     {output_json}")

    # Load existing sampling results
    existing_sampling = load_from_jsonl(sampling_jsonl)
    completed_unique_ids = {r['unique_id'] for r in existing_sampling}

    print(f"Found {len(existing_sampling)} existing sampling results")
    print(f"Completed unique IDs: {len(completed_unique_ids)}")

    # Filter out completed questions (use unique_id to handle repetitions)
    results_to_process = [r for r in results if r['unique_id'] not in completed_unique_ids]
    print(f"Questions to process: {len(results_to_process)}")

    return results_to_process, experiment_metadata, model_type, (sampling_jsonl, output_json)


def build_sampling_tasks(results_to_process, args, model_type):
    """
    Build all sampling tasks (questions × n samples)

    Returns:
        Tuple of (all_tasks, question_metadata)
    """
    print(f"\n=== Building all tasks (questions × n samples) ===")
    all_tasks = []
    question_metadata = {}  # Map unique_id to metadata

    for result_item in results_to_process:
        question_id = result_item['question_id']
        unique_id = result_item['unique_id']
        question = result_item['question']
        ground_truth = result_item['ground_truth']
        processed_reasoning = result_item['processed_reasoning']

        # Store question metadata (use unique_id as key to handle repetitions)
        question_metadata[unique_id] = {
            'question_id': question_id,
            'unique_id': unique_id,
            'question': question,
            'ground_truth': ground_truth,
            'processed_reasoning': processed_reasoning
        }

        # Create n tasks for this question using the helper function
        for sample_id in range(args.n):
            task = build_sampling_request(
                question=question,
                processed_reasoning=processed_reasoning,
                answer_free_gen=args.answer_free_gen,
                model_type=model_type,
                temperature=args.temperature,
                task_index=len(all_tasks),  # Global task index
                metadata={
                    'unique_id': unique_id,
                    'sample_id': sample_id
                }
            )
            all_tasks.append(task)

    total_tasks = len(all_tasks)
    print(f"Total tasks to process: {total_tasks} ({len(results_to_process)} questions × {args.n} samples)")
    print(f"Max workers: {args.max_workers}")

    return all_tasks, question_metadata


def execute_and_group_tasks(all_tasks, client, args, question_metadata, sampling_jsonl):
    """
    Execute all tasks in parallel with immediate JSONL writing

    When all N samples for a question are completed, immediately calculates
    distribution and writes to JSONL (thread-safe).

    Args:
        all_tasks: List of all tasks to execute
        client: LLM client instance
        args: Command line arguments (n, answer_free_gen, max_workers)
        question_metadata: Dict mapping unique_id to question metadata
        sampling_jsonl: Path to JSONL file for immediate saving

    Returns:
        None (results are written to JSONL immediately)
    """
    import threading
    from collections import defaultdict

    print(f"\n=== Executing all tasks with immediate JSONL writing ===")

    # Thread-safe tracking
    lock = threading.Lock()
    samples_by_question = defaultdict(list)
    completed_count = defaultdict(int)
    saved_questions = set()  # Track which questions have been saved

    with tqdm(total=len(all_tasks), desc="Sampling") as pbar:
        for completed_task in client.complete_concurrent(all_tasks, max_workers=args.max_workers):
            unique_id = completed_task.metadata['unique_id']

            # Process task response
            sample = process_completed_task(completed_task, args.answer_free_gen)

            # Thread-safe update and check for completion
            with lock:
                samples_by_question[unique_id].append(sample)
                completed_count[unique_id] += 1

                # Check if all samples for this question are completed
                if completed_count[unique_id] == args.n and unique_id not in saved_questions:
                    # Mark as saved to prevent duplicate writes
                    saved_questions.add(unique_id)

                    # Get metadata
                    meta = question_metadata[unique_id]
                    samples = samples_by_question[unique_id]

                    # Sort samples by sample_id
                    samples.sort(key=lambda x: x['sample_id'])

                    # Calculate distribution
                    distribution = calculate_distribution(samples, meta['ground_truth'])

                    # Calculate summary stats
                    total_valid_samples = sum(1 for s in samples if s.get('success') and s.get('extracted_answer'))
                    total_invalid_samples = len(samples) - total_valid_samples

                    # Build result
                    sampling_result = {
                        'unique_id': meta['unique_id'],
                        'question_id': meta['question_id'],
                        'question': meta['question'],
                        'ground_truth': meta['ground_truth'],
                        'processed_reasoning': meta['processed_reasoning'],
                        'samples': samples,
                        'distribution': distribution,
                        'total_samples': len(samples),
                        'total_valid_samples': total_valid_samples,
                        'total_invalid_samples': total_invalid_samples,
                    }

                    # Append to JSONL immediately (thread-safe with lock)
                    append_to_jsonl(sampling_jsonl, sampling_result)

            # Update progress bar
            pbar.update(1)

    print(f"\n=== All tasks completed, {len(saved_questions)} questions saved to JSONL ===")


def generate_final_output(sampling_jsonl, output_json, args, experiment_metadata, model_type):
    """
    Generate final output JSON from JSONL results
    """
    print(f"\n=== Building final output ===")

    # Reload all sampling results (to ensure we have everything)
    all_sampling_results = load_from_jsonl(sampling_jsonl)

    # Sort by question_id
    all_sampling_results.sort(key=lambda x: x['question_id'])

    # Calculate summary statistics
    total_questions = len(all_sampling_results)
    avg_top1_accuracy = sum(
        r['distribution'][0]['is_correct'] if r['distribution'] else False
        for r in all_sampling_results
    ) / total_questions if total_questions > 0 else 0

    # Calculate average entropy (Shannon entropy of distribution)
    avg_entropy = sum(
        calculate_entropy(r['distribution'])
        for r in all_sampling_results
    ) / total_questions if total_questions > 0 else 0

    summary = {
        'total_questions': total_questions,
        'avg_top1_accuracy': avg_top1_accuracy,
        'avg_entropy': avg_entropy,
        'n_samples': args.n,
        'answer_free_gen': args.answer_free_gen,
        'temperature': args.temperature
    }

    # Build metadata
    output_metadata = {
        'source_result': args.result,
        'n_samples': args.n,
        'answer_free_gen': args.answer_free_gen,
        'model': model_type,
        'temperature': args.temperature,
        'timestamp': datetime.now().isoformat(),
        'source_experiment_metadata': experiment_metadata
    }

    # Final output structure
    final_output = {
        'metadata': output_metadata,
        'summary': summary,
        'results': all_sampling_results
    }

    # Save final JSON
    with open(output_json, 'w', encoding='utf-8') as f:
        json.dump(final_output, f, indent=2, ensure_ascii=False)

    print(f"\n{'='*60}")
    print(f"DISTRIBUTION ANALYSIS COMPLETE")
    print(f"{'='*60}")
    print(f"Total questions:        {summary['total_questions']}")
    print(f"Samples per question:   {args.n}")
    print(f"Avg top-1 accuracy:     {summary['avg_top1_accuracy']:.2%}")
    print(f"Avg entropy:            {summary['avg_entropy']:.4f}")
    print(f"{'='*60}")
    print(f"\nSampling JSONL: {sampling_jsonl}")
    print(f"Final JSON:     {output_json}")


# =============================================================================
# Main Entry Point
# =============================================================================

def main():
    """Main entry point"""
    # Parse arguments
    parser = argparse.ArgumentParser(
        description='Analyze answer distribution from reasoning chain sampling'
    )
    parser.add_argument(
        '--result',
        type=str,
        required=True,
        help='Path to input results.json'
    )
    parser.add_argument(
        '--out',
        type=str,
        default=None,
        help='Path to output distributions.json (default: same directory as --result with filename distributions.json)'
    )
    parser.add_argument(
        '--n',
        type=int,
        default=DEFAULT_N_SAMPLES,
        help=f'Number of samples per question (default: {DEFAULT_N_SAMPLES})'
    )
    parser.add_argument(
        '--answer_free_gen',
        action='store_true',
        help='Enable answer-free generation (no prefill text)'
    )
    parser.add_argument(
        '--max_workers',
        type=int,
        default=DEFAULT_MAX_WORKERS,
        help=f'Maximum number of concurrent workers (default: {DEFAULT_MAX_WORKERS})'
    )
    parser.add_argument(
        '--temperature',
        type=float,
        default=DEFAULT_TEMPERATURE,
        help=f'Sampling temperature (default: {DEFAULT_TEMPERATURE})'
    )
    parser.add_argument(
        '--mode',
        type=str,
        default='openrouter',
        choices=['openrouter', 'local'],
        help='LLM client mode (default: openrouter)'
    )
    parser.add_argument(
        '--limit',
        type=int,
        default=None,
        help='Limit number of questions to process (for testing)'
    )

    args = parser.parse_args()

    # Set default output path if not provided
    if args.out is None:
        result_path = Path(args.result)
        args.out = str(result_path.parent / 'distributions.json')

    # Print configuration
    print(f"Answer Distribution Analysis")
    print(f"=" * 60)
    print(f"Input:           {args.result}")
    print(f"Output:          {args.out}")
    print(f"Samples (n):     {args.n}")
    print(f"Answer-free gen: {args.answer_free_gen}")
    print(f"Max workers:     {args.max_workers}")
    print(f"Temperature:     {args.temperature}")
    print(f"=" * 60)

    # Execute pipeline
    results_to_process, experiment_metadata, model_type, (sampling_jsonl, output_json) = load_and_validate_input(args)

    # Initialize LLM client
    client = LLMClient(mode=args.mode)

    # Build tasks
    all_tasks, question_metadata = build_sampling_tasks(results_to_process, args, model_type)

    # Execute tasks with immediate JSONL writing
    execute_and_group_tasks(all_tasks, client, args, question_metadata, sampling_jsonl)

    # Generate final output
    generate_final_output(sampling_jsonl, output_json, args, experiment_metadata, model_type)


if __name__ == '__main__':
    main()
